const STORE_TYPE = "profile";

export const ADD_DATA = `${STORE_TYPE}/ADD_DATA`;
export const CLEAR_DATA = `${STORE_TYPE}/CLEAR_DATA`;
export const CHANGE_FLAG_UPDATED_DATA = `${STORE_TYPE}/CHANGE_FLAG_UPDATED_DATA`;
