const STORE_TYPE = "films";

export const GET_FILMS_LIST = `${STORE_TYPE}/GET_FILMS_LIST`;
export const GET_FILMS_LIST_SUCCESS = `${STORE_TYPE}/GET_FILMS_LIST_SUCCESS`;
export const GET_FILMS_LIST_FAILURE = `${STORE_TYPE}/GET_FILMS_LIST_FAILURE`;
