const STORE_TYPE = "taxi";

export const GET_ADDRESSLIST = `${STORE_TYPE}/GET_ADDRESSLIST`;
export const GET_ADDRESSLIST_SUCCESS = `${STORE_TYPE}/GET_ADDRESSLIST_SUCCESS`;
export const GET_ADDRESSLIST_FAILURE = `${STORE_TYPE}/GET_ADDRESSLIST_FAILURE`;

export const GET_ROUTE = `${STORE_TYPE}/GET_ROUTE`;
export const GET_ROUTE_SUCCESS = `${STORE_TYPE}/GET_ROUTE_SUCCESS`;
export const GET_ROUTE_FAILURE = `${STORE_TYPE}/GET_ROUTE_FAILURE`;

export const GET_WEATHER = `${STORE_TYPE}/GET_WEATHER`;
export const GET_WEATHER_SUCCESS = `${STORE_TYPE}/GET_WEATHER_SUCCESS`;
export const GET_WEATHER_FAILURE = `${STORE_TYPE}/GET_WEATHER_FAILURE`;

export const CHANGE_FLAG_ROUTE = `${STORE_TYPE}/CHANGE_FLAG_ROUTE`;
