const STORE_TYPE = "people";

export const GET_PEOPLE_LIST = `${STORE_TYPE}/GET_PEOPLE_LIST`;
export const GET_PEOPLE_LIST_SUCCESS = `${STORE_TYPE}/GET_PEOPLE_LIST_SUCCESS`;
export const GET_PEOPLE_LIST_FAILURE = `${STORE_TYPE}/GET_PEOPLE_LIST_FAILURE`;

export const CLEAR_PEOPLE_LIST = `${STORE_TYPE}/CLEAR_PEOPLE_LIST`;
