const STORE_TYPE = "followers";

export const FOLLOWERS_REQUEST = `${STORE_TYPE}/FOLLOWERS_REQUEST`;
export const FOLLOWERS_SUCCESS = `${STORE_TYPE}/FOLLOWERS_SUCCESS`;
export const FOLLOWERS_FAILURE = `${STORE_TYPE}/FOLLOWERS_FAILURE`;
